import { ITEM } from '../core/constants.js';
import { MENU_BGM_CHOICES, RACE_BGM_CHOICES } from '../audio/bgm.js';

// English-only UI copy for the current release. Keeping presentation strings
// together makes a later localization pass mechanical without adding locale
// state or a language selector now.
export const UI_COPY = Object.freeze({
  title: {
    heading: 'MAIN MENU',
    items: [
      { value: 'single', icon: '🏁', label: 'SINGLE PLAYER', desc: 'Race against 7 AI drivers' },
      { value: 'multiplayer', icon: '🌐', label: 'MULTIPLAYER', desc: 'Browse public and friends-only online rooms' },
      { value: 'settings', icon: '⚙️', label: 'SETTINGS', desc: 'Audio and game options' },
      { value: 'help', icon: '📖', label: 'HELP', desc: 'Controls, items and racing tips' },
    ],
    hint: 'Arrows / WASD to navigate · Enter to select · M to mute',
    multiplayerToast: 'OPENING ONLINE PLAY',
  },
  character: {
    heading: 'PICK YOUR RACER',
    hint: 'Arrows to browse · Enter to pick · Esc to go back',
  },
  track: {
    heading: 'CHOOSE A TRACK',
    hint: 'Enter to select · Esc to go back',
  },
  difficulty: {
    heading: 'DIFFICULTY',
    hint: 'Enter to race · Esc to go back',
    flavor: {
      easy: { icon: '☀️', desc: 'Relaxed rivals, gentle items. A sunny Sunday drive.' },
      normal: { icon: '🏁', desc: 'A proper race. The pack fights back — so should you.' },
      hard: { icon: '🔥', desc: 'Ruthless AI, maximum rubber-band. Bring mushrooms.' },
    },
  },
  pause: {
    heading: 'PAUSED',
    items: [
      ['resume', 'RESUME'],
      ['settings', 'SETTINGS'],
      ['help', 'HELP'],
      ['restart', 'RESTART'],
      ['quit', 'QUIT TO TITLE'],
    ],
  },
  results: {
    heading: 'RACE RESULTS',
    racer: 'Racer',
    time: 'Time',
    bestLap: 'Best Lap',
    continue: 'Press Enter to continue',
  },
  settings: {
    heading: 'SETTINGS',
    rows: [
      { key: 'muted', kind: 'toggle', label: 'MUTE ALL', desc: 'Silence every audio channel' },
      { key: 'master', kind: 'volume', label: 'MASTER VOLUME', desc: 'Overall game volume' },
      { key: 'musicEnabled', kind: 'toggle', label: 'BACKGROUND MUSIC', desc: 'Enable the soundtrack' },
      { key: 'music', kind: 'volume', label: 'MUSIC VOLUME', desc: 'Soundtrack level' },
      { key: 'menuBgm', kind: 'choice', label: 'MENU BGM', desc: 'Music used across the main menus', options: MENU_BGM_CHOICES },
      { key: 'raceBgm', kind: 'choice', label: 'RACE BGM', desc: 'Default follows the selected track', options: RACE_BGM_CHOICES },
      { key: 'sfx', kind: 'volume', label: 'SFX VOLUME', desc: 'Engines, items and interface sounds' },
    ],
    reset: 'RESET TO DEFAULTS',
    back: 'BACK',
    hint: 'Up / Down to select · Left / Right to adjust · Esc to go back',
  },
  help: {
    heading: 'HELP',
    tabs: [
      { value: 'controls', label: 'CONTROLS' },
      { value: 'items', label: 'ITEMS' },
      { value: 'gameplay', label: 'GAMEPLAY' },
    ],
    back: 'BACK',
    hint: 'Left / Right changes tab · Up / Down scrolls · Esc goes back',
  },
  online: {
    menu: {
      label: 'MENU',
      settings: 'SETTINGS',
      help: 'HELP',
    },
    alerts: {
      genericTitle: 'ONLINE REQUEST FAILED',
      joinTitle: 'UNABLE TO JOIN ROOM',
      createTitle: 'UNABLE TO CREATE ROOM',
      quickTitle: 'QUICK START UNAVAILABLE',
      roomTitle: 'ROOM ACTION FAILED',
      connectionTitle: 'CONNECTION PROBLEM',
      dismiss: 'OK',
    },
    connection: {
      connecting: 'CONNECTING',
      connected: 'ONLINE',
      reconnecting: 'RECONNECTING',
      disconnected: 'OFFLINE',
      error: 'CONNECTION ERROR',
    },
    lobby: {
      eyebrow: 'ONLINE MULTIPLAYER',
      heading: 'MULTIPLAYER LOBBY',
      subtitle: 'Find a race, join friends, or create a room of your own.',
      back: 'BACK TO TITLE',
      playerSetup: 'Player setup',
      nickname: 'NICKNAME',
      nicknamePlaceholder: 'Enter your racer name',
      quickMatch: 'QUICK START',
      createRoom: 'CREATE ROOM',
      availableRooms: 'LIVE DIRECTORY',
      roomList: 'AVAILABLE ROOMS',
      search: 'Search rooms',
      searchPlaceholder: 'Search room, host, or code',
      newRoom: 'NEW ROOM',
      roomName: 'ROOM NAME',
      defaultRoomName: 'Turbo Room',
      unnamedRoom: 'Unnamed Room',
      unknownHost: 'Unknown racer',
      roomType: 'ROOM TYPE',
      publicRoom: 'Public - no password',
      privateRoom: 'Friends - password required',
      maxPlayers: 'PLAYER LIMIT',
      password: 'PASSWORD',
      passwordPlaceholder: '4-20 characters',
      passwordHelp: 'Passwords are case-sensitive.',
      enterPassword: 'Enter the room password',
      publicBadge: 'PUBLIC',
      privateBadge: 'FRIENDS',
      passwordRequired: 'Password required',
      noPasswordRequired: 'No password required',
      friendRoom: 'FRIENDS ROOM',
      joinRoom: 'JOIN ROOM',
      players: 'PLAYERS',
      host: 'HOST',
      statusLabel: 'Status',
      status: {
        waiting: 'WAITING',
        full: 'FULL',
        in_game: 'IN GAME',
      },
      join: 'JOIN',
      create: 'CREATE',
      cancel: 'CANCEL',
      close: 'Close dialog',
      roomFull: 'This room is full.',
      roomInGame: 'This room is already racing.',
      noRooms: 'No rooms are available yet',
      noRoomsHint: 'Create a room or wait for another racer to open one.',
      noSearchResults: 'No rooms match your search',
      tryAnotherSearch: 'Try a room name, host nickname, or six-character code.',
      roomCount: '{count} rooms online',
      searchCount: '{count} matching rooms',
      inviteLocated: 'Invite found: {roomName}',
      inviteMissing: 'Room {roomCode} is not currently available.',
    },
    room: {
      eyebrow: 'RACE ROOM',
      unnamedRoom: 'ONLINE ROOM',
      copyInvite: 'Copy invite link',
      copied: 'INVITE LINK COPIED',
      copyFallback: 'INVITE LINK COPIED',
      copyFailed: 'The invite link could not be copied. Please try again.',
      publicRoom: 'PUBLIC',
      privateRoom: 'FRIENDS',
      playerCount: '{count}/{max} RACERS',
      racers: 'RACERS',
      chooseRacer: 'CHOOSE YOUR RACER',
      raceSetup: 'RACE SETUP',
      track: 'TRACK',
      difficulty: 'AI DIFFICULTY',
      hostControls: 'You are the host. Setup changes reset everyone\'s ready state.',
      hostOnly: 'Only the host can change the race setup.',
      openSlot: 'Open slot',
      choosing: 'Choosing racer…',
      taken: 'TAKEN',
      you: 'YOU',
      host: 'HOST',
      ready: 'READY',
      notReady: 'NOT READY',
      inGame: 'IN GAME',
      offline: 'OFFLINE',
      leave: 'LEAVE ROOM',
      readyUp: 'READY UP',
      cancelReady: 'CANCEL READY',
      start: 'START RACE',
      loading: 'Loading the race…',
      waitingForRacer: 'Waiting for at least one more racer',
      readyCount: '{ready} / {total} racers ready',
      readyToStart: 'Everyone is ready — start the race!',
      waitingForHost: 'Everyone is ready — waiting for the host',
      phase: {
        loading: 'Loading the race…',
        countdown: 'The race is starting…',
        racing: 'Race in progress.',
        results: 'Waiting for racers to return to the room.',
      },
    },
    results: {
      official: 'OFFICIAL RESULTS',
      heading: 'RACE COMPLETE',
      place: 'Place',
      racer: 'Racer',
      time: 'Time',
      bestLap: 'Best Lap',
      returnRoom: 'RETURN TO ROOM',
      returnHint: 'Return to the room when you are ready.',
      autoReturn: 'Returning to the room automatically in {seconds}s.',
    },
    errors: {
      nickname: 'Enter a nickname before going online.',
      roomCode: 'Enter a valid 6-character room code.',
      ROOM_CODE_INVALID: 'The invite link has an invalid room code. Room codes must be exactly 6 valid characters.',
      ROOM_NAME_INVALID: 'Enter a room name between 1 and 32 characters.',
      ROOM_TYPE_INVALID: 'Choose a valid room type.',
      ROOM_CAPACITY_INVALID: 'Choose a player limit between 2 and 8.',
      PASSWORD_REQUIRED: 'Enter a case-sensitive password between 4 and 20 characters.',
      PASSWORD_INVALID: 'That room password is incorrect.',
      NO_MATCHING_ROOM: 'No joinable public room is available right now.',
      generic: 'Something went wrong. Please try again.',
    },
  },
});

export const HELP_CONTROLS = Object.freeze([
  {
    title: 'KEYBOARD',
    rows: [
      ['Steer', 'A / D or ← / →'],
      ['Accelerate', 'W or ↑'],
      ['Brake / Reverse', 'S or ↓'],
      ['Hop / Drift', 'Space or Shift'],
      ['Use Item', 'Ctrl, E or Enter'],
      ['Look Back', 'R'],
      ['Live Standings', 'Hold Tab'],
      ['Pause / Back', 'Esc'],
      ['Mute', 'M'],
    ],
  },
  {
    title: 'GAMEPAD',
    rows: [
      ['Steer', 'Left Stick / D-pad'],
      ['Accelerate', 'RT or A'],
      ['Brake / Reverse', 'LT or B'],
      ['Hop / Drift', 'RB or X'],
      ['Use Item', 'LB or Y'],
      ['Look Back', 'Right Stick Down'],
      ['Pause', 'Start'],
      ['Menu Back', 'B'],
    ],
  },
  {
    title: 'TOUCH',
    rows: [
      ['Accelerate', 'Automatic'],
      ['Steer', 'Drag in the left side of the screen'],
      ['Hop / Drift', 'Drift button'],
      ['Use Item', 'Item button'],
    ],
  },
]);

export const HELP_ITEM_ORDER = Object.freeze([
  ITEM.BANANA,
  ITEM.GREEN_SHELL,
  ITEM.RED_SHELL,
  ITEM.BLUE_SHELL,
  ITEM.MUSHROOM,
  ITEM.TRIPLE_MUSHROOM,
  ITEM.BOMB,
  ITEM.STAR,
  ITEM.LIGHTNING,
  ITEM.BULLET,
]);

export const HELP_ITEM_DESCRIPTIONS = Object.freeze({
  [ITEM.BANANA]: 'Drops behind your kart and spins out the next racer who hits it.',
  [ITEM.GREEN_SHELL]: 'Travels in a straight line and bounces off walls. Hold Look Back to fire it behind you.',
  [ITEM.RED_SHELL]: 'Tracks the nearest racer ahead. Hold Look Back to launch it backward instead.',
  [ITEM.BLUE_SHELL]: 'Hunts the race leader and explodes in a wide blast near first place.',
  [ITEM.MUSHROOM]: 'Grants a strong burst of speed for overtaking or cutting through rough ground.',
  [ITEM.TRIPLE_MUSHROOM]: 'Stores three separate mushroom boosts in one item pickup.',
  [ITEM.BOMB]: 'Throws forward and explodes after landing. Hold Look Back to plant it behind your kart.',
  [ITEM.STAR]: 'Temporarily boosts your speed, makes you invulnerable and knocks rivals aside.',
  [ITEM.LIGHTNING]: 'Shrinks and slows every opponent currently ahead of you.',
  [ITEM.BULLET]: 'Transforms your kart into a high-speed autopilot that charges through the field.',
});

export const HELP_GAMEPLAY = Object.freeze([
  { icon: '🏆', title: 'FINISH FIRST', text: 'Eight racers compete over the track\'s required lap count. Cross the final line ahead of the pack.' },
  { icon: '🚦', title: 'ROCKET START', text: 'Press accelerate just before GO for an opening boost. Holding it too early causes a jump-start penalty.' },
  { icon: '🌀', title: 'DRIFT BOOSTS', text: 'Hop while steering and keep drifting. Release after blue, orange or purple sparks for increasingly stronger boosts.' },
  { icon: '🎁', title: 'ITEM BOXES', text: 'Drive through item boxes to start the roulette. Racers farther behind receive stronger comeback items.' },
  { icon: '⚡', title: 'KEEP YOUR SPEED', text: 'Hit boost pads, chain drift boosts and follow rivals closely to charge a slipstream boost.' },
  { icon: '👀', title: 'USE ITEMS SMARTLY', text: 'Look backward while using shells or Bob-ombs to defend your position from racers behind.' },
]);
